name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  appimage-ubuntu:
    name: Appimage-ubuntu
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: date +%F > todays-date
      - name: Restore cache for today's nightly.
        uses: actions/cache@v2
        with:
          path: |
            build
          key: ${{ runner.os }}-appimage-${{ hashFiles('todays-date') }}

      - name: Prepare
        run: |
          test -d build || {
            mkdir -p build
            wget https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage
            chmod +x nvim.appimage
            mv nvim.appimage ./build/nvim
          }
          make test-deps
      - name: Run tests
        run: |
            export PATH="${PWD}/build/:${PATH}"
            make test
